apiVersion: v1
kind: ReplicationController
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world
