apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hello-world
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: hello-world
    ports:
    - containerPort: 6379
      hostPort: 1234
      name: api
