id: maokai
apiVersion: v1
kind: Pod

spec:
  containers:
    - name: www
      image: docker.web.dm/apache-php
      ports:
        - containerPort: 80
          hostPort: 8080

      volumeMounts:
        - name: consul
          hostPath: etc/production/consul.json
          mountPath: /etc/consul.d/web.json

        - name: httpd
          hostPath: etc/production/httpd.conf
          mountPath: /etc/httpd/vhost.d/default.conf

      env:
        - name: CONSUL_SERVER
          value: 115.29.54.118
        - name: RUN_MODE
          value: production
